### ISSUE TITLE
There are too many decimals displayed for currencies

### ISSUE THREAD

**Issue by KirienzoEth** [DungeonEthereum/Dungeon-Ethereum-Website#8]
It can get the UI pretty clogged up, like so:
Home page:
![image](https://user-images.githubusercontent.com/72258256/95073214-6c8a2f80-0747-11eb-8475-902477113973.png)

Raid page:
![image](https://user-images.githubusercontent.com/72258256/95073300-95aac000-0747-11eb-861b-6ff32875de68.png)

It seems like the rest of the site has a 4 decimals limit, is that enough or should we go lower ?

**Comment by DungeonEthereum** [comment]
Maybe 2 decimals enough, or max 4
