### ISSUE TITLE
Add a countdown for the raid's block

### ISSUE THREAD

**Issue by KirienzoEth** [DungeonEthereum/Dungeon-Ethereum-Website#9]
Right now, you can only see the block number for the next raid, it's not very clear how much time do you have until this block.
etherscan provides an API endpoint for the countdown: https://etherscan.io/apis -> https://api.etherscan.io/api?module=block&action=getblockcountdown&blockno=11003515&apikey=YourApiKeyToken

**Note:** we need an API key if we don't want a limit of 1 request every 5 seconds.

**Comment by KirienzoEth** [comment]
Maybe display a message like "ENTER NOW !" when the time is right ? I guess we need to enter the raid after block 11003514 has been mined, but before 11003515 is mined (for the first raid for example).

It should prevent some users from missing the timeframe.

**Comment by DungeonEthereum** [comment]
Dont like the idea with a message, because the goal is to make it not too easy to join the raid
But a countdown would help to allow the users to have a better idea when the raid block will happen

**Comment by KirienzoEth** [comment]
https://github.com/DungeonEthereum/Dungeon-Ethereum-Website/pull/16 Should be good for a V1, until we can get an etherscan API key.
